#!/bin/bash

set -eo pipefail

#
# This script starts up the test process.
#
# - Environment settings (e.g. git config) are initialized
# - Terminus plugins are installed
# - Any needed code updates are done
#

# Carlos's note -- we need to set $TERMINUS_ENV = Branch Name (if not a Master push)
#   Additionally, we need to check for the Lock flag (in Dev for development / business user testing)
#   Once we have correct tests in place, we can ignore the Lock Flag

# ./.circleci/scripts/pantheon/01-yale-prepare
if [ "$CIRCLE_BRANCH" != "master" ]; then
  DEFAULT_ENV=$CIRCLE_BRANCH
  TERMINUS_ENV={$TERMINUS_SITE:$CIRCLE_BRANCH}
fi
echo "Begin build for $DEFAULT_ENV. Pantheon test environment is $TERMINUS_SITE.$TERMINUS_ENV"

# Log in via Terminus
terminus -n auth:login --machine-token="$TERMINUS_TOKEN"

# Delete leftover CI environments
# carlos's note-- we do not necessarrily want to delete these as we are going to change the environment ($TERMINUS_ENV) to be the Branch Name
terminus -n build:env:delete:ci "$TERMINUS_SITE" --keep=2 --yes
