#!/bin/bash

set -eo pipefail

echo "in Yale version of setting default_env"
if [ "$CIRCLE_BRANCH" != "master" ]; then
  (
    echo "export DEFAULT_ENV='$CIRCLE_BRANCH'"
    echo 'export TERMINUS_ENV=${TERMINUS_ENV:$CIRCLE_BRANCH}'
  ) >> $BASH_ENV
  source $BASH_ENV
fi
echo "leaving yale prepare and default_env is set to $DEFAULT_ENV and TERMINUS_ENV is $TERMINUS_ENV"
