#!/bin/bash

set -eo pipefail

#
# This script runs any post-test operations that may be needed.
#

if [ "$CIRCLE_BRANCH" != "master" ]; then
  TERMINUS_ENV=$CIRCLE_BRANCH
fi
terminus -n secrets:set "$TERMINUS_SITE.$TERMINUS_ENV" token "$GITHUB_TOKEN" --file='github-secrets.json' --clear --skip-if-empty
