definitions:
  contact__site_page:
    weight: -44
    menu_name: convenience
    parent: ''
    expanded: false
    enabled: true
  standard__front_page:
    weight: -45
    enabled: false
    menu_name: main
    parent: ''
    expanded: false
_core:
  default_config_hash: jdY7AU0tU-QsjmiOw3W8vwpYMb-By--_MSFgbqKUTYM
