<?php

/**
 * @file
 * Contains som_gnam_migrate.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

use Drupal\migrate\Row;
use Drupal\migrate\Plugin\MigrateSourceInterface;
use Drupal\migrate\Plugin\MigrationInterface;
/**
 * Implements hook_help().
 */
function som_gnam_migrate_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the som_gnam_migrate module.
    case 'help.page.som_gnam_migrate':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Migrating GNAM content from D7') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_uninstall().
 */
function som_gnam_migrate_uninstall() {
  // Not sure if this helps us or not
//  $configs  = [
//    'migrate_plus.migration.gnam_file',
//    'migrate_plus.migration.gnam_member_school',
//    'migrate_plus.migration.gnam_migrate_vocabulary',
//  ];
//  foreach($configs as $config) {
//    Drupal::configFactory()->getEditable($name)->delete();
//  }
//  drupal_flush_all_caches();
}

/**
 * Implements hook_migrate_MIGRATION_ID_prepare_row().
 *
 */
function som_gnam_migrate_migrate_gnam_node_teams_prepare_row(Row $row, MigrateSourceInterface $source, \Drupal\migrate\Plugin\MigrationInterface$migration) {
  $values    = $row->getSourceProperty('field_team_members');
  $value_new = [];
  if ($values) {
    foreach ($values as $value) {
      $value_new[] = ['item_id' => $value['value']];
    }
    $row->setSourceProperty('field_team_member_new', $value_new);
  }
}

/**
 * Implements hook_migrate_prepare_row().
 */
//function som_gnam_migrate_migrate_prepare_row(Row $row, MigrateSourceInterface $source, MigrationInterface $migration) {
//  xdebug_break();
//}

//function gnam_cas_migrate ($source_value) {
//  xdebug_break();
//  return $source_value;
//}